version: '3.4'

# Services overrides for running on GPU

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-fooocus-cuda}:${DOCKER_TAG:-latest}
    build:
      args:
        PYTHON_BASE: ${PYTHON_BASE:-rocm}
    # Deploy override
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
